name: Publish Package to npmjs
on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@ambrosus'
      
      - run: npm install
      - run: npm run build

      - name: Determine npm tag
        id: get_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" == "release" ]; then
            echo "::set-output name=tag::latest"
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's:.*/::')
            if [ "${{ github.event_name }}" == "release" ]; then
              TAG_NAME=$(echo "${{ github.event.release.tag_name }}" | sed 's/v//')
              echo "::set-output name=tag::${BRANCH_NAME}-${TAG_NAME}"
            else
              echo "::set-output name=tag::${BRANCH_NAME}"
            fi
          fi

      - run: npm publish --tag ${{ steps.get_tag.outputs.tag }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
